# Generated by Django 2.2.3 on 2019-09-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaya', '0002_product_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
